import src.controllers.quiz_info_controller as quiz_info_controller
import src.controllers.chatbot_controller as chatbot_controllers
import src.controllers.planets_list_controller as planets_list_controllers